#!/bin/bash
# Assistant sandbox container entrypoint. See arch_wiki/dmh_ai/isolation.md.
#
# Sets up the network fence on container start, then spawns the
# browser daemon under a supervisor loop, then blocks on `tail`.
#
#   1. Disable IPv6 entirely (simpler than maintaining a parallel
#      ip6tables ruleset).
#   2. DNS bypass for Docker's embedded resolver at 127.0.0.11
#      (every UID needs DNS to reach the public internet).
#   3. ACCEPT outbound from UID 10000 (dmh_ai-master-u, admin) BEFORE
#      the REJECT rules — first match wins, so admin's exec'd
#      commands reach the LAN. Per-user UIDs (10001+) fall through.
#   4. REJECT outbound to RFC1918 / loopback / link-local for the
#      remaining UIDs.
#   5. Spawn the Playwright daemon under a `while true; do; done`
#      restart loop in the background. The loop respects an idle-
#      shutdown exit (the daemon kills itself after no traffic for
#      `BROWSER_IDLE_SHUTDOWN_S`); the next request relaunches it.
#
# Per-user OS accounts are added lazily by master via `docker exec
# sandbox useradd -u <uid> dmh_ai-u<uid>` — see
# DmhAi.Permissions.SandboxUser.

set -e

# --- IPv6 off ----------------------------------------------------------------
# Best effort: containers may have these as sysctls already locked at
# the Docker daemon level. If a sysctl is read-only the line errors;
# we don't want to block container start for that — fall through.
sysctl -w net.ipv6.conf.all.disable_ipv6=1     2>/dev/null || true
sysctl -w net.ipv6.conf.default.disable_ipv6=1 2>/dev/null || true
sysctl -w net.ipv6.conf.lo.disable_ipv6=1      2>/dev/null || true

# --- iptables fence ----------------------------------------------------------
if command -v iptables >/dev/null 2>&1; then
    # Docker embedded DNS resolver lives at 127.0.0.11 inside the
    # netns. Every UID needs DNS to reach the public internet, so
    # both directions bypass the loopback REJECT below — query
    # (dst=127.0.0.11) and reply (src=127.0.0.11) both traverse
    # OUTPUT, and the reply is generated by an in-netns daemon
    # socket with no associated UID, so the owner match cannot
    # catch it. Without these two rules, getaddrinfo times out for
    # every user (admin included).
    iptables -A OUTPUT -d 127.0.0.11 -j ACCEPT 2>/dev/null || true
    iptables -A OUTPUT -s 127.0.0.11 -j ACCEPT 2>/dev/null || true

    # Admin pass-through. UID 10000 = dmh_ai-master-u. First-match-
    # wins ordering: this ACCEPT must come before the REJECTs below.
    iptables -A OUTPUT -m owner --uid-owner 10000 -j ACCEPT 2>/dev/null || \
        echo "[sandbox start.sh] WARN: failed to add admin ACCEPT rule (CAP_NET_ADMIN missing?)"

    # LAN-wide REJECTs — apply to every other UID (10001+).
    iptables -A OUTPUT -d 127.0.0.0/8     -j REJECT 2>/dev/null || true
    iptables -A OUTPUT -d 10.0.0.0/8      -j REJECT 2>/dev/null || true
    iptables -A OUTPUT -d 172.16.0.0/12   -j REJECT 2>/dev/null || true
    iptables -A OUTPUT -d 192.168.0.0/16  -j REJECT 2>/dev/null || true
    iptables -A OUTPUT -d 169.254.0.0/16  -j REJECT 2>/dev/null || true
else
    echo "[sandbox start.sh] WARN: iptables not present — LAN fence not applied"
fi

# --- Browser daemon (Phase 2 of #215) ----------------------------------------
# One Playwright daemon per container, BrowserContext-per-user.
# Listens on /var/run/dmh-browser/daemon.sock; the deployment's
# docker-compose binds this directory out so the host-side Elixir
# process can connect.
#
# Supervisor pattern: spawn-and-restart. The daemon self-terminates
# after BROWSER_IDLE_SHUTDOWN_S of no traffic to free Chromium memory
# on Pi-class hosts; the supervisor relaunches it on the next call.
# A 2s pause between restarts prevents tight crash loops if the
# daemon fails to start (missing socket directory, port bound, etc.).
mkdir -p /var/run/dmh-browser
chmod 0775 /var/run/dmh-browser

(
    while true; do
        echo "[sandbox] spawning browser daemon"
        /sandbox-browser-daemon.py 2>&1 | sed 's/^/[browser_daemon] /' || true
        echo "[sandbox] browser daemon exited; restarting in 2s"
        sleep 2
    done
) &

# --- Stay alive --------------------------------------------------------------
exec tail -f /dev/null
