# Copyright (c) 2026 Cuong Truong
# This project is licensed under the AGPL v3.
# See the LICENSE file in the repository root for full details.
# For commercial inquiries, contact: tduccuong@gmail.com

defmodule DmhAi.Duolang.Tutor do
  @moduledoc """
  The tutor's spoken prose, generated by the model in the learner's **source
  language**. Three surfaces, one per moment in a phase:

    * `briefing/3`   — opens a phase: what it is, what they'll do, "say ready".
    * `completion/3` — closes a phase: congratulations + "ready for the next?".
    * `answer/3`     — a clarifying reply when the learner asks mid-gate.

  Nothing here is hardcoded per language — the model is handed the topic, the
  lesson, the level, and which phase this is, and writes the copy in the source
  language itself, so every language the app supports reads naturally. A short
  neutral fallback covers a model failure so a phase never opens blank.
  """

  alias DmhAi.Agent.{AgentSettings, LLM}
  alias DmhAi.Commands.Languages

  # Beats group into phases (`read` + `check` are both the Understand phase);
  # {label, goal} is keyed by phase. `label` names it; `goal` describes what the
  # learner does — both feed the model prompt in English, as facts to render
  # into source-language prose.
  @phase_of %{
    "recall" => :review,
    "read" => :understand,
    "check" => :understand,
    "speak" => :speak,
    "use" => :talk,
    "takeaway" => :recap
  }
  @phase_meta %{
    review: {"Review", "review a few words they have met before"},
    understand:
      {"Read & Understand",
       "read the short passage shown above them, then answer a few questions so you can check they followed it"},
    speak:
      {"Pronounce",
       "practise saying each line out loud — make it clear this phase is driven by the buttons on the material above them (they tap the speaker to hear a line, the microphone to say it back, then the Next-sentence button to move on), and that the chat below is open only if they want to ask you something"},
    talk:
      {"Roleplay",
       "step into a role-play with you, entirely in the target language, based on today's scenario: they play one side of the conversation and TYPE their replies in the target language, and it keeps going turn by turn until they can genuinely hold the exchange — make clear this is hands-on conversation practice, not a quiz, and that they should just reply in character to your opening line"},
    recap: {"Recap", "look back at the one thing to fix, then move to the next lesson"}
  }

  @doc "A phase-opening briefing in the source language."
  @spec briefing(map(), String.t(), String.t()) :: String.t()
  def briefing(course, beat, title) do
    {label, goal} = phase(beat)
    target = language_name(course.target_lang)
    source = language_name(course.source_lang)

    # `speak` has no readiness gate — its drill starts immediately and is driven
    # by the buttons, so the briefing must NOT ask them to say they're ready.
    closing =
      if @phase_of[beat] == :speak do
        "The first line is already on the stage above. Tell them to start practising it now with the buttons, and make clear you are here in the chat only if they have a question — do NOT ask them to say they are ready."
      else
        "Finish by inviting them to type that they are ready to begin, or to ask a question first."
      end

    system = """
    You are a warm, encouraging language tutor writing to a learner of #{target}.
    Write a SHORT briefing (2 to 4 sentences) that opens the "#{label}" phase of today's lesson.

    Weave these facts in naturally:
    - They are learning #{target} at CEFR level #{course.current_level}.
    - Course topic: #{course.topic}.
    - Today's lesson: #{title}.
    - In this phase they will #{goal}.

    Say warmly what this phase is and what they will do, referring to the material shown above them
    where it helps. #{closing} You may put the topic, the level, and the lesson title in **bold**.

    Write ENTIRELY in #{source}. Plain text, no preamble, no headings.
    """

    call(course, "briefing", system, "Write the briefing now.",
      fallback: "Let's begin the #{label} phase. Say you're ready when you'd like to start, or ask me anything first."
    )
  end

  @doc "A phase-closing congratulations + consent prompt, in the source language."
  @spec completion(map(), String.t(), String.t()) :: String.t()
  def completion(course, done_beat, next_beat) do
    {done_label, _} = phase(done_beat)
    {next_label, _} = phase(next_beat)
    target = language_name(course.target_lang)
    source = language_name(course.source_lang)

    system = """
    You are a warm, encouraging language tutor. The learner has just finished the "#{done_label}"
    phase of a #{target} lesson (topic: #{course.topic}).

    Write a SHORT message (1 to 2 sentences): warmly congratulate them on finishing this phase, then
    ask whether they are ready to move on to the "#{next_label}" phase, or have any questions first.

    Write ENTIRELY in #{source}. Plain text, no preamble.
    """

    call(course, "completion", system, "Write the message now.",
      fallback: "Nice work finishing #{done_label}! Ready to move on to #{next_label}, or any questions first?"
    )
  end

  @doc """
  Answer a clarifying question the learner asks, in the source language, using
  the passage when one is on the stage. `context` says HOW they continue from
  here, so the closing reminder never contradicts what they're actually doing:

    * `:brief`    — a briefing gate; they say they're ready to begin.
    * `:complete` — a completion gate; they say they're ready to move on.
    * `:speak`    — the button-driven speak drill; there is NO "ready" step, so
      the answer must not mention it — it points back to the buttons instead.
  """
  @spec answer(map(), :brief | :complete | :speak, String.t() | nil, String.t()) :: String.t()
  def answer(course, context, passage, input) do
    target = language_name(course.target_lang)
    source = language_name(course.source_lang)

    continue =
      case context do
        :brief ->
          "After answering, let them know they can say they're ready whenever they'd like to begin."

        :complete ->
          "After answering, let them know they can say they're ready to move on to the next phase whenever they like."

        :speak ->
          "Reply with only the answer to their question, in one or two warm sentences. They are mid-way through a hands-on speaking drill and carry on with the buttons on their own, so end the moment the question is answered."
      end

    system = """
    You are a warm tutor helping someone learn #{target}. They asked a question while working through
    the lesson. Answer their question briefly and helpfully in #{source}. #{continue}
    Plain text, no preamble.
    """

    user =
      "Their question: #{input}" <>
        if passage in [nil, ""], do: "", else: "\n\nPassage (numbered lines):\n#{passage}"

    reply = call(course, "answer", system, user, fallback: "")
    # The model reflexively ends answers with a "ready to move on" sign-off; in
    # the button-driven speak drill that's wrong (nothing is moving on), so drop
    # a trailing sign-off there. The two gates keep theirs — they invite it.
    if context == :speak, do: strip_signoff(reply), else: reply
  end

  # Words that mark a generic "let me know when you're ready / move on" sign-off,
  # across the source languages the app supports.
  @signoff_markers [
    "ready",
    "let me know",
    "move on",
    "next phase",
    "whenever you",
    "sẵn sàng",
    "cho tôi biết",
    "chuyển sang",
    "giai đoạn",
    "bereit",
    "sag mir",
    "wissen lässt",
    "nächste phase",
    "listo",
    "avísame",
    "siguiente fase",
    "cuando quieras",
    "prêt",
    "prête",
    "dis-moi",
    "phase suivante",
    "quand tu veux"
  ]

  # Drop a trailing sign-off — the model puts it after a blank line, so peel the
  # last paragraph when it reads like one; fall back to peeling the last sentence
  # when the whole reply is one block.
  defp strip_signoff(text) do
    case String.split(text, ~r/\n{2,}/) do
      [_ | _] = parts when length(parts) > 1 ->
        if signoff?(List.last(parts)),
          do: parts |> Enum.drop(-1) |> Enum.join("\n\n") |> String.trim(),
          else: text

      _ ->
        sentences = String.split(text, ~r/(?<=[.!?])\s+/)

        if length(sentences) > 1 and signoff?(List.last(sentences)),
          do: sentences |> Enum.drop(-1) |> Enum.join(" ") |> String.trim(),
          else: text
    end
  end

  defp signoff?(para), do: String.contains?(String.downcase(para), @signoff_markers)

  # ── internals ──────────────────────────────────────────────────────────

  defp phase(beat), do: Map.get(@phase_meta, @phase_of[beat], {beat, "continue the lesson"})

  defp call(course, kind, system, user, opts) do
    case LLM.call(
           AgentSettings.confidant_model(),
           [%{role: "system", content: system}, %{role: "user", content: user}],
           options: %{temperature: 0.6},
           trace: trace(course, kind)
         ) do
      {:ok, text} when is_binary(text) ->
        case String.trim(text) do
          "" -> Keyword.fetch!(opts, :fallback)
          trimmed -> trimmed
        end

      _ ->
        Keyword.fetch!(opts, :fallback)
    end
  end

  defp language_name(code) do
    case Languages.by_code(code) do
      %{english: name} -> name
      _ -> code
    end
  end

  defp trace(course, kind) do
    %{
      origin: "duolang",
      path: "Duolang.Tutor.#{kind}",
      role: "Duolang",
      phase: kind,
      user_id: Map.get(course, :user_id),
      tier: :swift
    }
  end
end
