# Copyright (c) 2026 Cuong Truong
# This project is licensed under the AGPL v3.
# See the LICENSE file in the repository root for full details.
# For commercial inquiries, contact: tduccuong@gmail.com

defmodule DmhAi.Agent.AgentSettings do
  @moduledoc """
  Reads per-agent model configuration from admin_cloud_settings.
  Falls back to sensible defaults so the system works out of the box.
  """

  alias DmhAi.Repo
  import Ecto.Adapters.SQL, only: [query!: 3]

  # Defaults use the canonical `<pool>::<model>` format. See
  # specs/api_pools.md. The `ollama-cloud` pool is seeded on first boot
  # from the operator's pool seed file (defaults to placeholder zero
  # accounts; admin must add their cloud accounts via System Settings →
  # API Pools before these models can be used).
  # Two-tier model layout (see specs/architecture.md §Model tiers):
  #
  #   confidantModel — Confidant answer. Conversational, image-capable.
  #   swiftModel     — Swift tier. Short, single-shot decisions:
  #                    fact extraction, Web.Search query planner,
  #                    session naming, /tts + /duolang segmentation.
  #                    Cheapest model — latency dominates over quality.
  #   oracleModel    — Oracle tier. Long, dense content processing:
  #                    web result synthesis. Strong general model.
  #   visionModel    — Vision/OCR. Image describe, video describe,
  #                    PDF OCR. Must be image-capable.
  #   kbEmbeddingModel — Embedder for the confidant memory stores
  #                    (facts.db / memos.db). See
  #                    arch_wiki/dmh_ai/facts_memos.md.
  @defaults %{
    "confidantModel"   => "ollama-cloud::gemma4:31b-cloud",
    "swiftModel"       => "ollama-cloud::gemma4:31b-cloud",
    "oracleModel"      => "ollama-cloud::gemma4:31b-cloud",
    "visionModel"      => "ollama-cloud::gemma4:31b-cloud",
    "kbEmbeddingModel" => "miner::qwen3-embedding:0.6b"
  }

  @log_trace_default false
  @model_behavior_telemetry_enabled_default true

  @max_tool_result_chars_default 8_000
  @max_assistant_turns_per_chain_default 50

  # Target ceiling (in chars) for ANY tool's final output. This is a
  # *target the model is taught to honor*, not a runtime truncation —
  # tool results are kept verbatim in context. The model is taught to
  # consume intermediate data inside its script (head / tail / grep /
  # jq / awk pipelines) so the tool's emit lands well under this cap.
  # Verbose dumps (full `ls -R`, raw HTML, unfiltered `find /`) belong
  # INSIDE the script as intermediate steps, never as the result that
  # rides into the next turn's context. Interpolated into the system
  # prompt + the `run_script` tool description.
  @tool_result_target_chars_default 4_000

  # Compaction thresholds — see architecture.md §Compaction. The runtime
  # keeps the conversation tail bounded by replacing oldest rounds with
  # an LLM-generated summary message at chain start. A "round" is one
  # user message plus the assistant chain it triggered.
  #
  # `compaction_high_water_chars` — trigger threshold; total tail chars
  # above this triggers a compaction pass.
  # `compaction_low_water_chars` — target tail size after compaction.
  # The cut point is selected to bring the tail at or below this floor
  # WHENEVER that's compatible with `compaction_keep_recent_rounds`.
  # `compaction_keep_recent_rounds` — minimum number of complete rounds
  # always preserved verbatim, even when that keeps the tail above
  # low-water. Floor wins over low-water target.
  # `compaction_summary_max_tokens` — LLM-call budget for the summary
  # text generated by `DmhAi.Agent.Compactor`.
  @compaction_high_water_chars_default 30_000
  @compaction_low_water_chars_default 15_000
  @compaction_keep_recent_rounds_default 2
  @compaction_summary_max_tokens_default 1_500

  # Cap on the number of `run_script` calls per single chain. The
  # (N+1)th run_script is rejected by Police's run_script_probe_budget
  # gate with a nudge that teaches the model to compose the rest into
  # ONE more script OR ask the user the specific question probes can't
  # answer. Default 5: leaves room for genuinely complex API
  # discovery (probe stages → probe methods → probe fields → execute
  # → verify) while still surfacing scope walls and missing entities
  # to the user fast. See architecture.md §Police gate #11.
  @run_script_probe_budget_default 5

  # Total state-changing tool failures allowed in one assistant
  # chain before the dispatcher refuses any further write attempts.
  # Catches the runaway shape where the model emits
  # `upsert_workflow` / `*.send` / `*.create` over and over with
  # varying-but-broken args (different errors each time, so the
  # identical-error check doesn't trip). Hitting this budget forces
  # the model into a final-text turn that the phantom-outcome
  # auditor then gates. Read-class tools have no equivalent budget
  # because they don't mutate anything and the model self-correcting
  # by exploring is cheap.
  @write_failure_budget_per_chain_default 5

  # Long-running tool execution (see architecture.md
  # §Long-running tool execution). Every `run_script` invocation is
  # wrapped in nohup, registered in `DmhAi.Agent.RunningTools`, and
  # the runtime polls process status every `tool_run_poll_interval_ms`.
  # Anything still running after `run_script_max_runtime_ms` is
  # killed and returns `{:error, "max_runtime exceeded after Ns"}`.
  @tool_run_poll_interval_ms_default 2_000
  @run_script_max_runtime_ms_default 21_600_000

  # `mk_download_link` per-call size cap. Files larger than this are
  # rejected — keeps a runaway `cp /var/log/syslog` (or worse, a model
  # publishing a 50 GB DB dump) from filling user_assets.
  @publish_max_bytes_default 50_000_000

  # `mk_download_link` URL signature TTL. A signed link works
  # without a bearer token until expiry, so the URL can be shared
  # with non-DMH-AI users. Default 7 days bounds the blast radius
  # if a link is over-shared.
  @publish_link_ttl_secs_default 604_800

  # Document extraction
  @min_extracted_text_chars_default 50
  @ocr_pages_per_chunk_default 8
  @ocr_page_cap_default 16

  # Rolling tool-result flush — how many turns AFTER its emit_turn a
  # `role: "tool"` message stays visible in the LLM message array. Each
  # tool result is tagged at insertion with the chain turn index that
  # produced it; before each subsequent LLM call the runtime drops tool
  # messages where `(current_turn - emit_turn) > retention`. The
  # assistant's text and the `tool_call` args themselves are NEVER
  # flushed — only the verbose `role: "tool"` body. Default 1: a tool
  # result is visible to the NEXT turn only; by turn N+2 (where the
  # call was emitted in turn N) it has been dropped. See architecture.md
  # §Rolling tool-result flush.
  @tool_result_retention_turns_default 1

  # Auto session naming. The Data handler's `post_name_session` pulls
  # the last N user messages (slash commands skipped) and feeds them
  # to a swift-tier LLM. On a refresh-rename it also passes the
  # current title so the model can bridge the old framing with the
  # new direction (continuity over snap-to-latest). See arch §Session
  # naming.
  @session_namer_user_msg_count_default 4

  # LLM-account rotation throttle durations. Applied by
  # `DmhAi.Agent.LLM` when an account hits a rate-limit (HTTP 429 or
  # stream-inline RL error) or has its quota exhausted (Ollama's
  # weekly cap). Rate-limit defaults to 60 s — matches the typical
  # upstream rolling-window RL and keeps a burst from locking the
  # whole account pool. Quota default is 168 h (7 days) to match
  # Ollama's weekly reset cadence. The 429 handler also parses the
  # `Retry-After` header and, when present, uses it in preference to
  # this default (see `parse_retry_after_ms/1`).
  @rate_limit_throttle_secs_default 60
  @quota_exhausted_throttle_hours_default 168

  # Global per-LLM-call attempt budget. Spans both within-account
  # retry-on-server-error AND cross-account rotation. When 0, the call
  # returns `{:error, :attempts_exhausted}` instead of looping. Without
  # this cap, a single-account pool whose endpoint returns a persistent
  # `5xx` (or transport error) loops indefinitely — `mark_throttled`
  # only fires for `:rate_limited`, so `:all_throttled` is unreachable
  # for `:server_error`. The cap is the only correct termination
  # condition for that shape. See arch_wiki §Retry cap.
  @llm_total_attempts_default 6

  # Outbound HTTP receive_timeout for LLM calls (both streaming and
  # non-streaming). Belt-and-suspenders cap so a stalled connection
  # fails out rather than blocking forever; not the primary defence
  # against hangs (that's `Connection: close` + `compressed: false`
  # in lib/dmh_ai/agent/llm.ex). Default 300 s accommodates cold-loads
  # of large local Ollama models when `num_ctx` forces a KV-cache
  # reallocation — the prior 120 s was too tight for 24B-class
  # models on consumer GPUs (see specs/api_pools.md §num_ctx).
  # Bump higher if your hardware reloads slower; lower if you'd
  # rather fail fast on misbehaving cloud endpoints.
  @llm_receive_timeout_ms_default 300_000

  # Wall-clock budget for the Confidant pre-step (web search planner +
  # memo retrieval, both run in parallel before the main answer
  # streams). When exceeded, the pre-step Task crashes; the chain ends
  # with a visible `chain_aborted` row instead of streaming an answer.
  # Default 60 s comfortably covers cloud Swift latencies and most
  # warm self-hosted models. Operators on slow miners that need
  # cold-load + non-streaming completion budget should bump this; the
  # tradeoff is a longer silent wait before the user sees the error
  # row when something is genuinely wedged.
  @confidant_pre_step_timeout_ms_default 60_000

  # Output-token ceiling (num_predict) passed to every assistant-mode
  # LLM.stream call. `num_predict` is a ceiling, NOT a prepaid budget
  # — unused headroom has no cost. Set far above any practical
  # tool_call or reply size (long bash scripts easily run to ~1 000
  # tokens) while still bounding a runaway model that never emits EOS.
  @llm_num_predict_assistant_default 16_384

  # Time-to-live (seconds) for a `request_input` form. After this,
  # the BE rejects late submissions and the FE renders the form as
  # expired. The chain that emitted the form stays paused — user can
  # re-ask in a new chain.
  @request_input_ttl_secs_default 600

  # OAuth2 pending-state TTL (seconds). State token mints when a
  # `connect_mcp` flow starts; expires N seconds later. Callbacks
  # past expiry are rejected.
  @oauth_state_ttl_secs_default 600

  # Base URL the BE uses to construct OAuth2 redirect URIs. Combined
  # with a state token to form `<base>/oauth/callback/<state>`. Must
  # match the redirect URI the provider's OAuth App / authorization
  # server allows (or its prefix, when the provider accepts a prefix).
  @oauth_redirect_base_url_default "http://localhost:8080"

  # Web / HTTP defaults
  @http_user_agent_default "Mozilla/5.0 (compatible; DMH-AI/1.0)"
  @searxng_url_default "http://127.0.0.1:8888"
  @jina_base_url_default "https://r.jina.ai/"
  @web_search_max_fetch_pages_default 6
  @web_search_fetch_content_budget_default 18_000
  @web_search_direct_timeout_ms_default 6_000
  @web_search_jina_timeout_ms_default 7_000
  @web_search_total_timeout_ms_default 20_000
  # Hard cap (chars) on raw web-search-results text injected into the
  # Confidant turn. Cuts boilerplate / ads / dup snippets at the tail
  # so the main Confidant LLM call doesn't choke on a 45 KB+ blob.
  # The framing block ("Web search results (retrieved DATE)…") already
  # tells the model to focus on relevant facts and ignore noise.
  @web_results_max_chars_default 12_000

  # Embedding model output dim + request batching for the confidant
  # memory stores (facts.db / memos.db). qwen3-embedding-0.6b emits
  # 1024-dim vectors; changing `kb_embedding_dim` requires a full
  # reindex (the SQLite-blob store rejects mismatched rows on insert).
  @kb_embedding_dim_default 1024
  @kb_embedding_batch_size_default 32

  # Confidant memory (facts.db / memos.db) — see arch_wiki/dmh_ai/facts_memos.md.
  # Max spellfix1 edit distance for a typo-repaired query token. spellfix1's
  # metric is scaled (~10 per single-char edit, ~40 for a longer-word typo,
  # 256 for unrelated); 200 accepts genuine typos and rejects noise.
  @kb_spellfix_max_distance_default 200
  # Unprocessed-user-message batch before the swift fact extractor fires.
  @fact_extract_batch_size_default 3
  # Top-K facts / memos surfaced into the <user_facts> / <user_memos> blocks.
  @user_facts_top_k_default 5
  @user_memos_top_k_default 5

  # Duolang tutor mode — see arch_wiki/dmh_ai/duolang_mode.md.
  # Items drawn for the recall beat, and new items introduced per session.
  # A session is a fixed size regardless of how far behind the learner is:
  # a due count grown during an absence is the un-gamified equivalent of a
  # broken streak, and is the likeliest way the learner abandons the tool.
  @duolang_session_recall_items_default 8
  @duolang_session_new_items_default 12
  # Sentences in a generated text, and prompts in the check beat. Retell
  # agreement with comprehension rises materially from one prompt to three.
  @duolang_text_sentence_count_default 6
  @duolang_retell_prompts_default 3
  # Upper bound on the AI-driven comprehension check. The tutor keeps asking
  # until the learner shows they understand; this only caps the loop so it
  # always terminates.
  @duolang_max_check_questions_default 5
  # Turn cap for the Roleplay (use) beat — deliberately large so the learner
  # must put in real effort before the model lets the exchange end. The model
  # can end sooner once they have genuinely earned it; this is the ceiling.
  @duolang_max_use_turns_default 8
  # Corrections surfaced live during the use beat. Everything past the cap
  # goes to the error ledger for a later session — one correction practised
  # well beats an exhaustive dump the learner cannot act on.
  @duolang_live_correction_cap_default 3
  # Coverage target for TUTORED reading (text met with a translation beside
  # it). The far higher figure quoted in the literature is for unassisted
  # independent reading and does not apply here.
  @duolang_coverage_target_default 85
  # Profiler rejection thresholds. Sentence length is judged on the HARDEST
  # sentence, not the mean — averaging hides the one sentence that stops
  # the learner.
  @duolang_max_token_miss_rate_default 15
  @duolang_max_sentence_words_default 18
  # Below this many known words, a miss RATE is arithmetically unreachable
  # — there is not yet a vocabulary for text to be familiar against — so
  # the generator governs by an absolute count of new words instead. The
  # bound is cognitive load per sitting, not coverage of a corpus.
  @duolang_vocabulary_floor_default 1000
  @duolang_cold_start_new_words_default 10
  # Generate → profile → repair attempts before falling back to the best
  # candidate seen. A model hits a named proficiency level only a small
  # fraction of the time, so the profiler is the authority, not the prompt.
  @duolang_generate_attempts_default 3
  # Fixed interval ladder in days. Fixed on purpose: expanding and equal
  # schedules perform equivalently, so an adaptive per-item scheduler buys
  # complexity and no measured gain.
  @duolang_interval_ladder_days_default [1, 3, 7, 16, 35]
  # Absence beyond which the next session shrinks and re-introduces rather
  # than tests, recording no incorrect results.
  @duolang_reentry_gap_days_default 10
  @duolang_reentry_scale_percent_default 50
  # Synthesis rate for modelling a row, as a percent of normal speed.
  @duolang_model_speech_rate_default 85
  # Recognition start timeout. An unavailable recognition language on
  # Android terminates with no error event and no end event, so a watchdog
  # is the only way to detect it.
  @duolang_asr_watchdog_ms_default 8000

  @doc """
  Get the model string for a given agent role. Returns the default if
  unset. Always in `<pool>::<model>` form (see specs/api_pools.md).
  Both the per-role override stored in `admin_cloud_settings` and the
  baked-in `@defaults` use this form.
  """
  @spec model_for(String.t()) :: String.t()
  def model_for(role) when is_binary(role) do
    settings = load()
    val = String.trim(settings[role] || "")
    if val == "", do: @defaults[role] || "", else: val
  end

  @doc "Whether to write verbatim LLM call traces to <session_root>/log_traces/<task_id>.log."
  @spec log_trace() :: boolean()
  def log_trace, do: bool_setting("logTrace", @log_trace_default)

  @doc "Whether to record model misbehavior occurrences to model_behavior_stats for the admin UI."
  @spec model_behavior_telemetry_enabled() :: boolean()
  def model_behavior_telemetry_enabled,
    do: bool_setting("modelBehaviorTelemetryEnabled", @model_behavior_telemetry_enabled_default)

  @doc "Shortcut accessors."
  def confidant_model,    do: model_for("confidantModel")
  def swift_model,        do: model_for("swiftModel")
  def oracle_model,       do: model_for("oracleModel")
  def vision_model,       do: model_for("visionModel")
  def kb_embedding_model, do: model_for("kbEmbeddingModel")

  @doc "Hard character limit for tool results fed back to the assistant. Larger results are truncated."
  @spec max_tool_result_chars() :: pos_integer()
  def max_tool_result_chars, do: int_setting("maxToolResultChars", @max_tool_result_chars_default)

  @doc "Target ceiling on any tool's final output size. Taught to the model via the system prompt; not enforced at runtime."
  @spec tool_result_target_chars() :: pos_integer()
  def tool_result_target_chars,
    do: int_setting("toolResultTargetChars", @tool_result_target_chars_default)

  @doc "Compaction trigger: total tail chars above this triggers a compaction pass."
  @spec compaction_high_water_chars() :: pos_integer()
  def compaction_high_water_chars,
    do: int_setting("compactionHighWaterChars", @compaction_high_water_chars_default)

  @doc "Compaction target: bring the tail at or below this many chars whenever compatible with `compaction_keep_recent_rounds`."
  @spec compaction_low_water_chars() :: pos_integer()
  def compaction_low_water_chars,
    do: int_setting("compactionLowWaterChars", @compaction_low_water_chars_default)

  @doc "Compaction floor: number of recent rounds (1 round = 1 user msg + 1 chain) always preserved verbatim."
  @spec compaction_keep_recent_rounds() :: pos_integer()
  def compaction_keep_recent_rounds,
    do: int_setting("compactionKeepRecentRounds", @compaction_keep_recent_rounds_default)

  @doc "Compaction summary LLM-call max_tokens budget."
  @spec compaction_summary_max_tokens() :: pos_integer()
  def compaction_summary_max_tokens,
    do: int_setting("compactionSummaryMaxTokens", @compaction_summary_max_tokens_default)

  @doc """
  Per-chain safety cap on the number of turns (LLM roundtrips) before the
  chain aborts with a carry-on message. Terminology: one **turn** is one
  LLM call + its tool execution; one **chain** is the sequence of turns
  until the assistant emits user-facing text. See architecture.md
  §Assistant Mode.
  """
  @spec max_assistant_turns_per_chain() :: pos_integer()
  def max_assistant_turns_per_chain, do: int_setting("maxAssistantTurnsPerChain", @max_assistant_turns_per_chain_default)

  @spec run_script_probe_budget() :: pos_integer()
  def run_script_probe_budget, do: int_setting("runScriptProbeBudget", @run_script_probe_budget_default)

  @spec write_failure_budget_per_chain() :: pos_integer()
  def write_failure_budget_per_chain,
    do: int_setting("writeFailureBudgetPerChain", @write_failure_budget_per_chain_default)

  @doc "Number of recent user messages fed to the auto session-namer LLM call."
  @spec session_namer_user_msg_count() :: pos_integer()
  def session_namer_user_msg_count,
    do: int_setting("sessionNamerUserMsgCount", @session_namer_user_msg_count_default)

  @doc "Runtime poll cadence (ms) for in-flight `run_script` processes."
  @spec tool_run_poll_interval_ms() :: pos_integer()
  def tool_run_poll_interval_ms,
    do: int_setting("toolRunPollIntervalMs", @tool_run_poll_interval_ms_default)

  @doc "Hard upper bound (ms) on a single `run_script` invocation. Past this the runtime kills the PID."
  @spec run_script_max_runtime_ms() :: pos_integer()
  def run_script_max_runtime_ms,
    do: int_setting("runScriptMaxRuntimeMs", @run_script_max_runtime_ms_default)

  @doc "Maximum size (bytes) of a single `mk_download_link` publish. Larger files are rejected."
  @spec publish_max_bytes() :: pos_integer()
  def publish_max_bytes,
    do: int_setting("publishMaxBytes", @publish_max_bytes_default)

  @doc "TTL (seconds) of a `mk_download_link` signed URL before the signature expires."
  @spec publish_link_ttl_secs() :: pos_integer()
  def publish_link_ttl_secs,
    do: int_setting("publishLinkTtlSecs", @publish_link_ttl_secs_default)

  @doc """
  Days after which completed `workflow_run_state` rows + their
  step trace get exported to JSONL archive and dropped from the
  live DB. Default 30. See `arch_wiki/dmh_ai/sme/layer-W.md`
  §Retention.
  """
  @spec workflow_run_retention_days() :: pos_integer()
  def workflow_run_retention_days,
    do: int_setting("workflowRunRetentionDays", 30)

  @doc """
  Days after a connector Discover succeeds before the FE shows a
  yellow "consider refreshing" indicator on that layer. Vendor
  surfaces drift (new fields, deprecated scopes, renamed methods);
  this is the soft nudge for the operator to walk each connector
  periodically.
  """
  @spec discovery_warn_after_days() :: pos_integer()
  def discovery_warn_after_days,
    do: int_setting("discoveryWarnAfterDays", 7)

  @doc """
  Days after a connector Discover succeeds before the FE shows a
  red "stale" indicator. Hard threshold — past this point the
  bundled defaults are assumed obsolete enough that the model's
  catalog likely diverges from the vendor.
  """
  @spec discovery_stale_after_days() :: pos_integer()
  def discovery_stale_after_days,
    do: int_setting("discoveryStaleAfterDays", 180)

  @doc """
  Install-wide HMAC secret used to sign per-workflow webhook URLs.
  Lazily generated on first call (32 random bytes, base64-encoded)
  and persisted in the `settings` table so the URL stays stable
  across restarts. If the operator rotates this value, EVERY armed
  webhook URL must be re-pasted into its external system — by
  design, the secret IS the binding.
  """
  @spec install_secret() :: String.t()
  def install_secret do
    settings = load()

    case settings["installSecret"] do
      v when is_binary(v) and v != "" ->
        v

      _ ->
        new_secret = 32 |> :crypto.strong_rand_bytes() |> Base.url_encode64(padding: false)
        # Persist alongside the other admin settings (one JSON blob
        # under the `admin_cloud_settings` key). Re-load + merge so we
        # don't clobber concurrent edits.
        DmhAi.Repo
        |> Ecto.Adapters.SQL.query!("""
        INSERT INTO settings (key, value)
        VALUES (?, ?)
        ON CONFLICT(key) DO UPDATE SET value = excluded.value
        """, [
          "admin_cloud_settings",
          Jason.encode!(Map.put(load(), "installSecret", new_secret))
        ])

        new_secret
    end
  end

  @doc "Minimum post-trim char count for an `extract_content` result to count as 'meaningful' (not blank/scanned)."
  @spec min_extracted_text_chars() :: pos_integer()
  def min_extracted_text_chars, do: int_setting("minExtractedTextChars", @min_extracted_text_chars_default)

  @doc "How many rendered PDF pages to send per vision-LLM OCR call."
  @spec ocr_pages_per_chunk() :: pos_integer()
  def ocr_pages_per_chunk, do: int_setting("ocrPagesPerChunk", @ocr_pages_per_chunk_default)

  @doc "Hard cap on PDF page count for OCR. Above this, extract_content fails with a nudge to split the file."
  @spec ocr_page_cap() :: pos_integer()
  def ocr_page_cap, do: int_setting("ocrPageCap", @ocr_page_cap_default)

  @doc "Number of recent turns whose tool_call / tool_result messages are retained in context."
  @spec tool_result_retention_turns() :: pos_integer()
  def tool_result_retention_turns,
    do: int_setting("toolResultRetentionTurns", @tool_result_retention_turns_default)

  @doc """
  Rate-limit throttle duration (seconds). Applied to an LLM account
  when it returns 429 / rate-limited AND the response carried no
  `Retry-After` header to honor. Default 60 s — a typical upstream
  rate-limit rolling window.
  """
  @spec rate_limit_throttle_secs() :: pos_integer()
  def rate_limit_throttle_secs,
    do: int_setting("rateLimitThrottleSecs", @rate_limit_throttle_secs_default)

  @doc """
  Global per-LLM-call attempt budget (across within-account retries
  AND cross-account rotation cycles). Default 6.
  """
  @spec llm_total_attempts() :: pos_integer()
  def llm_total_attempts,
    do: int_setting("llmTotalAttempts", @llm_total_attempts_default)

  @doc """
  Quota-exhausted throttle duration (hours). Applied when an LLM
  account signals its quota is spent (Ollama's "weekly usage limit"
  message). Default 168 h (7 days) to match Ollama cloud's weekly
  reset.
  """
  @spec quota_exhausted_throttle_hours() :: pos_integer()
  def quota_exhausted_throttle_hours,
    do: int_setting("quotaExhaustedThrottleHours", @quota_exhausted_throttle_hours_default)

  @doc """
  Outbound HTTP `receive_timeout` (ms) for both streaming and
  non-streaming LLM calls. Belt-and-suspenders cap so a stalled
  connection fails out rather than blocking forever. Default 300 s
  to absorb cold-loads of large local Ollama models when `num_ctx`
  forces a KV-cache reallocation.
  """
  @spec llm_receive_timeout_ms() :: pos_integer()
  def llm_receive_timeout_ms,
    do: int_setting("llmReceiveTimeoutMs", @llm_receive_timeout_ms_default)

  @doc "Wall-clock budget (ms) for Confidant's parallel web/memo pre-step."
  @spec confidant_pre_step_timeout_ms() :: pos_integer()
  def confidant_pre_step_timeout_ms,
    do: int_setting("confidantPreStepTimeoutMs", @confidant_pre_step_timeout_ms_default)

  @doc """
  Output-token ceiling (`num_predict`) applied to every assistant-mode
  LLM.stream call. A ceiling, not a reservation: unused headroom has
  no cost. Raise if long tool_calls (scripts, files) are getting cut
  mid-string; lower to harden against runaway generation.
  """
  @spec llm_num_predict_assistant() :: pos_integer()
  def llm_num_predict_assistant,
    do: int_setting("llmNumPredictAssistant", @llm_num_predict_assistant_default)

  @doc """
  Time-to-live (seconds) for a `request_input` form. The BE rejects
  submissions whose form is older than this; the FE renders the form
  as expired. The chain that emitted the form stays paused.
  """
  @spec request_input_ttl_secs() :: pos_integer()
  def request_input_ttl_secs,
    do: int_setting("requestInputTtlSecs", @request_input_ttl_secs_default)

  @doc "TTL (seconds) for pending OAuth2 state tokens before they expire."
  @spec oauth_state_ttl_secs() :: pos_integer()
  def oauth_state_ttl_secs,
    do: int_setting("oauthStateTtlSecs", @oauth_state_ttl_secs_default)

  @doc """
  Base URL the BE uses when constructing OAuth2 redirect URIs.
  Combined with a state token as `<base>/oauth/callback/<state>`.
  Must match the redirect URI (or its prefix) registered with the
  provider. Genuinely per-deployment — the BE listens on a single
  host; per-user OAuth App credentials are stored separately in
  `user_credentials`.
  """
  @spec oauth_redirect_base_url() :: String.t()
  def oauth_redirect_base_url,
    do: string_setting("oauth_redirect_base_url", @oauth_redirect_base_url_default)

  @doc "HTTP User-Agent string for outbound web requests."
  @spec http_user_agent() :: String.t()
  def http_user_agent, do: string_setting("httpUserAgent", @http_user_agent_default)

  @doc "SearXNG base URL."
  @spec searxng_url() :: String.t()
  def searxng_url, do: string_setting("searxngUrl", @searxng_url_default)

  @doc "Jina reader base URL (appended with the target URL)."
  @spec jina_base_url() :: String.t()
  def jina_base_url, do: string_setting("jinaBaseUrl", @jina_base_url_default)

  @doc "Max number of search-result pages fetched per web search cycle."
  @spec web_search_max_fetch_pages() :: pos_integer()
  def web_search_max_fetch_pages, do: int_setting("webSearchMaxFetchPages", @web_search_max_fetch_pages_default)

  @doc "Character budget for accumulated page content per web search cycle."
  @spec web_search_fetch_content_budget() :: pos_integer()
  def web_search_fetch_content_budget, do: int_setting("webSearchFetchContentBudget", @web_search_fetch_content_budget_default)

  @doc "HTTP receive timeout (ms) for direct page fetches in web_search."
  @spec web_search_direct_timeout_ms() :: pos_integer()
  def web_search_direct_timeout_ms, do: int_setting("webSearchDirectTimeoutMs", @web_search_direct_timeout_ms_default)

  @doc "HTTP receive timeout (ms) for Jina reader fetches."
  @spec web_search_jina_timeout_ms() :: pos_integer()
  def web_search_jina_timeout_ms, do: int_setting("webSearchJinaTimeoutMs", @web_search_jina_timeout_ms_default)

  @doc "Task.await_many timeout (ms) for the parallel fetch phase."
  @spec web_search_total_timeout_ms() :: pos_integer()
  def web_search_total_timeout_ms, do: int_setting("webSearchTotalTimeoutMs", @web_search_total_timeout_ms_default)

  @doc "Hard cap (chars) on raw web-search-results text injected into the Confidant turn."
  @spec web_results_max_chars() :: pos_integer()
  def web_results_max_chars,
    do: int_setting("webResultsMaxChars", @web_results_max_chars_default)

  @doc "Max spellfix1 edit distance for a typo-repaired query token (facts/memos)."
  @spec kb_spellfix_max_distance() :: pos_integer()
  def kb_spellfix_max_distance,
    do: int_setting("kbSpellfixMaxDistance", @kb_spellfix_max_distance_default)

  @doc "Unprocessed-user-message batch before the swift fact extractor fires."
  @spec fact_extract_batch_size() :: pos_integer()
  def fact_extract_batch_size,
    do: int_setting("factExtractBatchSize", @fact_extract_batch_size_default)

  @doc "Top-K facts surfaced into the <user_facts> block each LLM call."
  @spec user_facts_top_k() :: pos_integer()
  def user_facts_top_k, do: int_setting("userFactsTopK", @user_facts_top_k_default)

  @doc "Top-K memos surfaced into the <user_memos> block each LLM call."
  @spec user_memos_top_k() :: pos_integer()
  def user_memos_top_k, do: int_setting("userMemosTopK", @user_memos_top_k_default)

  # ── Duolang tutor mode ─────────────────────────────────────────────────

  @doc "Due items drawn for the recall beat. Fixed regardless of backlog size."
  @spec duolang_session_recall_items() :: pos_integer()
  def duolang_session_recall_items,
    do: int_setting("duolangSessionRecallItems", @duolang_session_recall_items_default)

  @doc "New items introduced per session."
  @spec duolang_session_new_items() :: pos_integer()
  def duolang_session_new_items,
    do: int_setting("duolangSessionNewItems", @duolang_session_new_items_default)

  @doc "Sentences in a generated lesson text."
  @spec duolang_text_sentence_count() :: pos_integer()
  def duolang_text_sentence_count,
    do: int_setting("duolangTextSentenceCount", @duolang_text_sentence_count_default)

  @doc "Retell prompts in the check beat."
  @spec duolang_retell_prompts() :: pos_integer()
  def duolang_retell_prompts,
    do: int_setting("duolangRetellPrompts", @duolang_retell_prompts_default)

  @doc "Upper bound on AI-driven comprehension questions in the check beat."
  @spec duolang_max_check_questions() :: pos_integer()
  def duolang_max_check_questions,
    do: int_setting("duolangMaxCheckQuestions", @duolang_max_check_questions_default)

  @doc "Upper bound on turns in the Roleplay (use) beat — the model may end sooner."
  @spec duolang_max_use_turns() :: pos_integer()
  def duolang_max_use_turns,
    do: int_setting("duolangMaxUseTurns", @duolang_max_use_turns_default)

  @doc "Maximum corrections surfaced live during the use beat."
  @spec duolang_live_correction_cap() :: pos_integer()
  def duolang_live_correction_cap,
    do: int_setting("duolangLiveCorrectionCap", @duolang_live_correction_cap_default)

  @doc "Known-word coverage target for tutored reading, percent."
  @spec duolang_coverage_target() :: pos_integer()
  def duolang_coverage_target,
    do: int_setting("duolangCoverageTarget", @duolang_coverage_target_default)

  @doc "Established-stage rejection threshold for unknown content tokens, percent."
  @spec duolang_max_token_miss_rate() :: pos_integer()
  def duolang_max_token_miss_rate,
    do: int_setting("duolangMaxTokenMissRate", @duolang_max_token_miss_rate_default)

  @doc "Known-word count below which cold-start rules govern generation."
  @spec duolang_vocabulary_floor() :: pos_integer()
  def duolang_vocabulary_floor,
    do: int_setting("duolangVocabularyFloor", @duolang_vocabulary_floor_default)

  @doc "Distinct new words a cold-start passage may introduce."
  @spec duolang_cold_start_new_words() :: pos_integer()
  def duolang_cold_start_new_words,
    do: int_setting("duolangColdStartNewWords", @duolang_cold_start_new_words_default)

  @doc "Profiler ceiling on the hardest sentence's word count."
  @spec duolang_max_sentence_words() :: pos_integer()
  def duolang_max_sentence_words,
    do: int_setting("duolangMaxSentenceWords", @duolang_max_sentence_words_default)

  @doc "Generate → profile → repair attempts before falling back to the best candidate."
  @spec duolang_generate_attempts() :: pos_integer()
  def duolang_generate_attempts,
    do: int_setting("duolangGenerateAttempts", @duolang_generate_attempts_default)

  @doc """
  Fixed interval ladder in days. A correct answer advances one step; an
  incorrect answer resets to step 0.
  """
  @spec duolang_interval_ladder_days() :: [pos_integer()]
  def duolang_interval_ladder_days,
    do: int_list_setting("duolangIntervalLadderDays", @duolang_interval_ladder_days_default)

  @doc "Absence in days beyond which the next session shrinks and re-introduces."
  @spec duolang_reentry_gap_days() :: pos_integer()
  def duolang_reentry_gap_days,
    do: int_setting("duolangReentryGapDays", @duolang_reentry_gap_days_default)

  @doc "Share of a normal session drawn on re-entry after an absence, percent."
  @spec duolang_reentry_scale_percent() :: pos_integer()
  def duolang_reentry_scale_percent,
    do: int_setting("duolangReentryScalePercent", @duolang_reentry_scale_percent_default)

  @doc "Synthesis rate for modelling a row, percent of normal speed."
  @spec duolang_model_speech_rate() :: pos_integer()
  def duolang_model_speech_rate,
    do: int_setting("duolangModelSpeechRate", @duolang_model_speech_rate_default)

  @doc "Recognition start timeout in ms; a missing language pack never fires an error."
  @spec duolang_asr_watchdog_ms() :: pos_integer()
  def duolang_asr_watchdog_ms,
    do: int_setting("duolangAsrWatchdogMs", @duolang_asr_watchdog_ms_default)

  @doc "Embedding vector dimension. Must match the embedding model's output. Changing this requires reindex."
  @spec kb_embedding_dim() :: pos_integer()
  def kb_embedding_dim, do: int_setting("kbEmbeddingDim", @kb_embedding_dim_default)

  @doc "How many texts the embedder packs into a single /embeddings request."
  @spec kb_embedding_batch_size() :: pos_integer()
  def kb_embedding_batch_size, do: int_setting("kbEmbeddingBatchSize", @kb_embedding_batch_size_default)

  @doc "User's chosen video detail level from admin settings. Returns 'low', 'medium', or 'high'."
  @spec video_detail() :: String.t()
  def video_detail do
    settings = load()
    case settings["videoDetail"] do
      v when v in ["low", "medium", "high"] -> v
      _ -> "medium"
    end
  end

  @doc """
  Canonical `<pool>::<model>` strings of all built-in system models in
  the `ollama-cloud` pool. Used by the FE model picker to render the
  baked-in cloud roster (operator-added pools/models extend this list
  but aren't surfaced here).
  """
  @spec system_model_names() :: [String.t()]
  def system_model_names do
    @defaults
    |> Map.values()
    |> Enum.uniq()
    |> Enum.filter(fn m -> String.starts_with?(m, "ollama-cloud::") end)
  end

  @doc "Map of every model-role setting key → its baked-in default name. Exposed to the FE via /admin/settings."
  @spec model_defaults() :: %{String.t() => String.t()}
  def model_defaults, do: @defaults

  defp string_setting(key, default) do
    settings = load()
    case settings[key] do
      s when is_binary(s) and s != "" -> s
      _ -> default
    end
  end

  defp bool_setting(key, default) do
    settings = load()
    case settings[key] do
      true    -> true
      false   -> false
      "true"  -> true
      "false" -> false
      _       -> default
    end
  end

  defp int_setting(key, default) do
    settings = load()
    case settings[key] do
      n when is_integer(n) and n > 0 -> n
      s when is_binary(s) ->
        case Integer.parse(s) do
          {n, _} when n > 0 -> n
          _ -> default
        end
      _ -> default
    end
  end

  # Ordered list of positive integers. Accepts a JSON array (as the admin
  # UI stores it) or a comma-separated string. Any malformed or non-positive
  # entry rejects the whole list back to the default rather than silently
  # yielding a partial ladder.
  defp int_list_setting(key, default) do
    parsed =
      case load()[key] do
        list when is_list(list) -> list
        s when is_binary(s) -> s |> String.split(",", trim: true) |> Enum.map(&String.trim/1)
        _ -> nil
      end

    case parsed do
      nil -> default
      [] -> default
      list -> list |> Enum.map(&to_positive_int/1) |> validate_int_list(default)
    end
  end

  defp to_positive_int(n) when is_integer(n) and n > 0, do: n

  defp to_positive_int(s) when is_binary(s) do
    case Integer.parse(s) do
      {n, ""} when n > 0 -> n
      _ -> :invalid
    end
  end

  defp to_positive_int(_), do: :invalid

  defp validate_int_list(list, default) do
    if Enum.any?(list, &(&1 == :invalid)), do: default, else: list
  end

  defp load do
    try do
      result = query!(Repo, "SELECT value FROM settings WHERE key=?", ["admin_cloud_settings"])

      case result.rows do
        [[v] | _] -> Jason.decode!(v || "{}")
        _ -> %{}
      end
    rescue
      _ -> %{}
    end
  end

  @doc """
  Per-org settings (Primitive 0.1). Reads `organizations.settings_json`
  layered over install-wide `admin_cloud_settings`. Per-key
  precedence: org override → install-wide → baked-in `@defaults`
  constant. Returns the merged map; pass it to the same
  `int_setting / bool_setting / float_setting / string_setting`
  shape via `get_in/2` if you need a single key.

  Falls back to the install-wide map if `org_id` is nil, empty, or
  not found.
  """
  @spec load_for_org(String.t() | nil) :: map()
  def load_for_org(nil), do: load()
  def load_for_org(""), do: load()

  def load_for_org(org_id) when is_binary(org_id) do
    install_wide = load()

    case org_overrides(org_id) do
      m when is_map(m) and map_size(m) > 0 -> Map.merge(install_wide, m)
      _ -> install_wide
    end
  end

  @doc """
  Pick a single setting with org-aware precedence: org override →
  install-wide → bound `default`. Mirrors the private `*_setting`
  helpers used by every accessor; exposed so per-org call sites can
  read a single key without re-implementing the merge.
  """
  @spec for_org(String.t() | nil, String.t(), any()) :: any()
  def for_org(org_id, key, default) when is_binary(key) do
    case load_for_org(org_id) |> Map.get(key) do
      nil -> default
      ""  -> default
      v   -> v
    end
  end

  defp org_overrides(org_id) do
    case query!(Repo, "SELECT settings_json FROM organizations WHERE id=?", [org_id]).rows do
      [[json]] when is_binary(json) and json != "" -> Jason.decode!(json)
      _ -> %{}
    end
  rescue
    _ -> %{}
  end
end
